# Generated by Django 6.0.6 on 2026-06-08 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_order_payment_fee_amount_and_more'),
        ('payments', '0002_currency_name_unique'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PaymentMethod',
        ),
    ]
