# Generated by Django 6.0.6 on 2026-06-09 09:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0004_order_receipt_number_branchreceiptsequence'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncedClientOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('synced_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sync_record', to='orders.order')),
            ],
            options={
                'ordering': ['-synced_at'],
            },
        ),
    ]
