RECEIPT_TYPE = "FiscalInvoice"
RECEIPT_PRINT_FORM = "Receipt48"
RECEIPT_LINE_TYPE = "Sale"
DEFAULT_MONEY_TYPE_CODE = "Cash"

ZERO_RATED_TAX_CODE = "B"
ZERO_RATED_TAX_ID = 2
STANDARD_TAX_CODE = "E"
DEFAULT_STANDARD_TAX_ID = 517
