# Generated by Django 6.0.6 on 2026-06-08 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='role',
            field=models.CharField(choices=[('hq_admin', 'HQ Admin'), ('branch_manager', 'Branch Manager'), ('cashier', 'Cashier'), ('baker', 'Baker'), ('staff', 'Staff')], default='cashier', max_length=20),
        ),
    ]
