# Generated by Django 6.0.6 on 2026-06-09 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='fiscalization_enabled',
            field=models.BooleanField(default=False, help_text='When enabled, sales from this branch are sent to the fiscal device.'),
        ),
    ]
