# Generated by Django 6.0.6 on 2026-06-09 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0002_branch_fiscalization_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='zimra_device_id',
            field=models.CharField(blank=True, help_text='ZIMRA fiscal device ID used in submit_receipt API path.', max_length=32),
        ),
    ]
