# Generated by Django 6.0.6 on 2026-06-09 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0003_branch_zimra_device_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='code',
            field=models.CharField(blank=True, help_text='3-letter receipt prefix, e.g. HIG for Highland, CHU for Churchill.', max_length=3),
        ),
    ]
