# Generated by Django 6.0.6 on 2026-06-25 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0005_branchtype_stores_central_stores'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiningTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dining_tables', to='branches.branch')),
            ],
            options={
                'ordering': ['sort_order', 'name'],
                'constraints': [models.UniqueConstraint(fields=('branch', 'name'), name='uniq_dining_table_per_branch')],
            },
        ),
    ]
