# Generated by Django 6.0.6 on 2026-06-22 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_stocktake_stocktakeline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverynote',
            name='invoice_number',
            field=models.CharField(blank=True, help_text='Transfer invoice number for central stores dispatches.', max_length=32, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='deliverynoteline',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Unit price on transfer invoices from central stores.', max_digits=10, null=True),
        ),
    ]
