# Generated by Django 6.0.6 on 2026-06-22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0004_delivery_note_invoice_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="deliverynote",
            name="paid_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the receiving branch settled this transfer invoice.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="deliverynote",
            name="paid_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Staff who recorded payment for this transfer invoice.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transfer_invoices_marked_paid",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="deliverynote",
            name="payment_status",
            field=models.CharField(
                choices=[("unpaid", "Unpaid"), ("paid", "Paid")],
                default="unpaid",
                help_text="Payment status for central stores transfer invoices.",
                max_length=10,
            ),
        ),
    ]
