# Generated by Django 6.0.6 on 2026-07-06 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_delivery_note_payment_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverynoteline',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Unit cost on transfer invoices from central stores.', max_digits=10, null=True),
        ),
    ]
