# Generated by Django 6.0.6 on 2026-07-10 10:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0008_branch_allow_negative_stock'),
        ('catalog', '0007_productcategory_pos_station'),
        ('inventory', '0007_centralinvoice_centralinvoiceline'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_before', models.DecimalField(decimal_places=2, max_digits=12)),
                ('delta', models.DecimalField(decimal_places=2, max_digits=12)),
                ('quantity_after', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reason', models.CharField(choices=[('manual_add', 'Manual add'), ('manual_set', 'Manual set'), ('sale', 'Sale'), ('sale_void', 'Sale void'), ('transfer_out', 'Transfer out'), ('transfer_in', 'Transfer in'), ('delivery_out', 'Delivery out'), ('delivery_in', 'Delivery in'), ('delivery_cancel', 'Delivery cancel'), ('production_consume', 'Production consume'), ('production_output', 'Production output'), ('stock_take', 'Stock take'), ('purchase', 'Purchase receive'), ('central_invoice', 'Central invoice'), ('central_invoice_cancel', 'Central invoice cancel'), ('adjustment', 'Adjustment')], default='adjustment', max_length=32)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('reference_type', models.CharField(blank=True, max_length=40)),
                ('reference_id', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='branches.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='catalog.product')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['branch', 'product', '-created_at'], name='inventory_s_branch__24bf87_idx'), models.Index(fields=['product', '-created_at'], name='inventory_s_product_cfb4fb_idx')],
            },
        ),
    ]
