# Generated by Django 6.0.6 on 2026-07-23 08:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_stockmovement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverynote',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliverynote',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_notes_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deliverynote',
            name='is_flagged',
            field=models.BooleanField(default=False, help_text='Flagged for follow-up when receipt differs from what was sent.'),
        ),
        migrations.AddField(
            model_name='deliverynote',
            name='remarks',
            field=models.TextField(blank=True, help_text='Receiving remarks captured on approve / confirm receipt.'),
        ),
        migrations.AddField(
            model_name='deliverynoteline',
            name='damaged_quantity',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Quantity rejected as damaged and returned to the sender.', max_digits=12),
        ),
        migrations.AddField(
            model_name='deliverynoteline',
            name='line_notes',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='deliverynoteline',
            name='received_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Good quantity accepted at the destination. Null until received.', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='reason',
            field=models.CharField(choices=[('manual_add', 'Manual add'), ('manual_set', 'Manual set'), ('sale', 'Sale'), ('sale_void', 'Sale void'), ('transfer_out', 'Transfer out'), ('transfer_in', 'Transfer in'), ('delivery_out', 'Delivery out'), ('delivery_in', 'Delivery in'), ('delivery_return', 'Delivery return'), ('delivery_cancel', 'Delivery cancel'), ('production_consume', 'Production consume'), ('production_output', 'Production output'), ('stock_take', 'Stock take'), ('purchase', 'Purchase receive'), ('central_invoice', 'Central invoice'), ('central_invoice_cancel', 'Central invoice cancel'), ('adjustment', 'Adjustment')], default='adjustment', max_length=32),
        ),
    ]
