# Generated by Django 6.0.6 on 2026-07-24 13:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0008_branch_allow_negative_stock'),
        ('catalog', '0008_productcategory_show_on_pos'),
        ('inventory', '0009_delivery_note_receipt_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='reason',
            field=models.CharField(choices=[('manual_add', 'Manual add'), ('manual_set', 'Manual set'), ('sale', 'Sale'), ('sale_void', 'Sale void'), ('transfer_out', 'Transfer out'), ('transfer_in', 'Transfer in'), ('delivery_out', 'Delivery out'), ('delivery_in', 'Delivery in'), ('delivery_return', 'Delivery return'), ('delivery_cancel', 'Delivery cancel'), ('production_consume', 'Production consume'), ('production_output', 'Production output'), ('stock_take', 'Stock take'), ('purchase', 'Purchase receive'), ('central_invoice', 'Central invoice'), ('central_invoice_cancel', 'Central invoice cancel'), ('wastage', 'Wastage'), ('wastage_transfer_in', 'Wastage transfer in'), ('adjustment', 'Adjustment')], default='adjustment', max_length=32),
        ),
        migrations.CreateModel(
            name='WastageEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reason', models.CharField(choices=[('bakery_reuse', 'Transferred for bakery reuse'), ('kitchen', 'Transferred to the kitchen'), ('disposal', 'Actual wastage/disposal')], max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('processed', 'Processed'), ('cancelled', 'Cancelled')], default='draft', max_length=12)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('branch', models.ForeignKey(help_text='Branch whose stock is reduced when this entry is processed.', on_delete=django.db.models.deletion.PROTECT, related_name='wastage_entries', to='branches.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wastage_entries_created', to=settings.AUTH_USER_MODEL)),
                ('destination_branch', models.ForeignKey(blank=True, help_text='Receiving branch for bakery reuse or kitchen transfer. Required when reason is bakery reuse.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incoming_wastage_entries', to='branches.branch')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wastage_entries_processed', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wastage_entries', to='catalog.product')),
            ],
            options={
                'verbose_name_plural': 'wastage entries',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['branch', '-created_at'], name='inventory_w_branch__2e1e34_idx'), models.Index(fields=['status', '-created_at'], name='inventory_w_status_919f4f_idx'), models.Index(fields=['reason', '-created_at'], name='inventory_w_reason_f778b5_idx')],
            },
        ),
    ]
