# Generated by Django 6.0.6 on 2026-07-28 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_wastage_entry_and_reasons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branchinventory',
            name='quantity',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='centralinvoiceline',
            name='quantity',
            field=models.DecimalField(decimal_places=3, max_digits=12),
        ),
        migrations.AlterField(
            model_name='deliverynoteline',
            name='damaged_quantity',
            field=models.DecimalField(decimal_places=3, default=0, help_text='Quantity rejected as damaged and returned to the sender.', max_digits=12),
        ),
        migrations.AlterField(
            model_name='deliverynoteline',
            name='quantity',
            field=models.DecimalField(decimal_places=3, max_digits=12),
        ),
        migrations.AlterField(
            model_name='deliverynoteline',
            name='received_quantity',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Good quantity accepted at the destination. Null until received.', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='delta',
            field=models.DecimalField(decimal_places=3, max_digits=12),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='quantity_after',
            field=models.DecimalField(decimal_places=3, max_digits=12),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='quantity_before',
            field=models.DecimalField(decimal_places=3, max_digits=12),
        ),
        migrations.AlterField(
            model_name='stocktakeline',
            name='counted_quantity',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='stocktakeline',
            name='system_quantity',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='stocktransfer',
            name='quantity',
            field=models.DecimalField(decimal_places=3, max_digits=12),
        ),
        migrations.AlterField(
            model_name='wastageentry',
            name='quantity',
            field=models.DecimalField(decimal_places=3, max_digits=12),
        ),
    ]
