# Generated by Django 6.0.6 on 2026-08-01 09:17

from django.conf import settings
from django.db import migrations, models
from django.db.models import Count


def cancel_duplicate_draft_stock_takes(apps, schema_editor):
    """Keep the oldest draft per period; cancel extras so the unique constraint can apply."""
    StockTake = apps.get_model("inventory", "StockTake")
    duplicates = (
        StockTake.objects.filter(status="draft")
        .values("branch_id", "stock_take_type", "count_date")
        .annotate(total=Count("id"))
        .filter(total__gt=1)
    )
    for group in duplicates:
        drafts = list(
            StockTake.objects.filter(
                status="draft",
                branch_id=group["branch_id"],
                stock_take_type=group["stock_take_type"],
                count_date=group["count_date"],
            ).order_by("created_at", "id")
        )
        keep = drafts[0]
        StockTake.objects.filter(
            pk__in=[draft.pk for draft in drafts[1:]],
        ).exclude(pk=keep.pk).update(status="cancelled")


class Migration(migrations.Migration):

    dependencies = [
        ("branches", "0008_branch_allow_negative_stock"),
        ("inventory", "0011_quantity_three_dp"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(
            cancel_duplicate_draft_stock_takes,
            migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name="stocktake",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "draft")),
                fields=("branch", "stock_take_type", "count_date"),
                name="unique_draft_stock_take_per_branch_period",
            ),
        ),
    ]
