# Generated by Django 6.0.6 on 2026-08-15 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_unique_draft_stock_take_per_branch_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktakeline',
            name='wastage_quantity',
            field=models.DecimalField(decimal_places=3, default=0, help_text='Quantity recorded as wastage/disposal during this count.', max_digits=12),
        ),
    ]
