# Generated by Django 6.0.6 on 2026-06-12 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ['product__name', 'ingredient__name'], 'verbose_name_plural': 'recipes'},
        ),
    ]
