# Generated by Django 6.0.6 on 2026-07-08 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0003_productionorder_branch_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='quantity_required',
            field=models.DecimalField(decimal_places=4, max_digits=12),
        ),
    ]
