# Generated by Django 6.0.6 on 2026-07-27 08:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0004_recipe_quantity_precision'),
        ('branches', '0008_branch_allow_negative_stock'),
        ('catalog', '0008_productcategory_show_on_pos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('production_date', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=12)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('branch', models.ForeignKey(help_text='Central bakery where production is recorded.', on_delete=django.db.models.deletion.PROTECT, related_name='production_sheets', to='branches.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_sheets_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-production_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductionSheetLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_sheet_lines', to='catalog.product')),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='bakery.productionsheet')),
            ],
            options={
                'ordering': ['product__category__name', 'product__name'],
            },
        ),
        migrations.CreateModel(
            name='ProductionSheetAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('destination_branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_sheet_allocations', to='branches.branch')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='bakery.productionsheetline')),
            ],
            options={
                'ordering': ['destination_branch__name'],
            },
        ),
        migrations.AddConstraint(
            model_name='productionsheet',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'completed')), fields=('branch', 'production_date'), name='unique_completed_production_sheet_per_bakery_day'),
        ),
        migrations.AlterUniqueTogether(
            name='productionsheetline',
            unique_together={('sheet', 'product')},
        ),
        migrations.AlterUniqueTogether(
            name='productionsheetallocation',
            unique_together={('line', 'destination_branch')},
        ),
    ]
