# Generated by Django 6.0.6 on 2026-07-27 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0005_production_sheet'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='productionsheet',
            name='unique_completed_production_sheet_per_bakery_day',
        ),
    ]
