# Generated by Django 6.0.6 on 2026-08-14 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0006_remove_production_sheet_daily_limit'),
        ('catalog', '0011_product_available_at_branches'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ['product__name', 'menu_addon__name', 'ingredient__name'], 'verbose_name_plural': 'recipes'},
        ),
        migrations.AlterUniqueTogether(
            name='recipe',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='recipe',
            name='menu_addon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='catalog.menuaddon'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipes_as_output', to='catalog.product'),
        ),
        migrations.AddConstraint(
            model_name='recipe',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('menu_addon__isnull', True), ('product__isnull', False)), models.Q(('menu_addon__isnull', False), ('product__isnull', True)), _connector='OR'), name='bakery_recipe_product_xor_menu_addon'),
        ),
        migrations.AddConstraint(
            model_name='recipe',
            constraint=models.UniqueConstraint(condition=models.Q(('product__isnull', False)), fields=('product', 'ingredient'), name='bakery_recipe_unique_product_ingredient'),
        ),
        migrations.AddConstraint(
            model_name='recipe',
            constraint=models.UniqueConstraint(condition=models.Q(('menu_addon__isnull', False)), fields=('menu_addon', 'ingredient'), name='bakery_recipe_unique_menu_addon_ingredient'),
        ),
    ]
