# Generated by Django 6.0.6 on 2026-09-17 06:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0007_recipe_menu_addon'),
        ('branches', '0009_highlands_dining_tables'),
        ('catalog', '0011_product_available_at_branches'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('needed_date', models.DateField(help_text="Date the products are needed (usually tomorrow's bake).")),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('accepted', 'Accepted'), ('fulfilled', 'Fulfilled'), ('cancelled', 'Cancelled')], default='draft', max_length=12)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('fulfilled_at', models.DateTimeField(blank=True, null=True)),
                ('bakery', models.ForeignKey(help_text='Central bakery that will produce the products.', on_delete=django.db.models.deletion.PROTECT, related_name='bakery_order_papers', to='branches.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_papers_created', to=settings.AUTH_USER_MODEL)),
                ('production_sheet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_papers', to='bakery.productionsheet')),
                ('requesting_branch', models.ForeignKey(help_text='Outlet or central stores that needs the products.', on_delete=django.db.models.deletion.PROTECT, related_name='order_papers', to='branches.branch')),
            ],
            options={
                'ordering': ['-needed_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderPaperLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_requested', models.DecimalField(decimal_places=2, max_digits=12)),
                ('quantity_accepted', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('order_paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='bakery.orderpaper')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_paper_lines', to='catalog.product')),
            ],
            options={
                'ordering': ['product__category__name', 'product__name'],
                'unique_together': {('order_paper', 'product')},
            },
        ),
    ]
