# Generated by Django 6.0.6 on 2026-06-23

import decimal
from decimal import Decimal

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("branches", "0005_branchtype_stores_central_stores"),
        ("customers", "0001_initial"),
        ("orders", "0009_order_fiscal_approval"),
        ("payments", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="account_balance",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0"),
                help_text="Prepaid balance in base currency.",
                max_digits=12,
            ),
        ),
        migrations.CreateModel(
            name="CustomerAccountTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[("deposit", "Deposit"), ("payment", "Payment")],
                        max_length=20,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Positive for deposits, negative for payments (base currency).",
                        max_digits=12,
                    ),
                ),
                ("balance_after", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "amount_received",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Amount received in payment currency (deposits only).",
                        max_digits=12,
                        null=True,
                    ),
                ),
                ("notes", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="customer_account_transactions",
                        to="branches.branch",
                    ),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        blank=True,
                        help_text="Cash currency received (deposits only).",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="customer_account_transactions",
                        to="payments.currency",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="account_transactions",
                        to="customers.customer",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="account_transactions",
                        to="orders.order",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="customer_account_transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
