# Generated by Django 6.0.6 on 2026-07-10 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customer_accounts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeraccounttransaction',
            name='transaction_type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('payment', 'Payment'), ('refund', 'Refund')], max_length=20),
        ),
    ]
