# Generated by Django 6.0.6 on 2026-07-13 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_order_cancel_void_and_account_refund'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='account_type',
            field=models.CharField(choices=[('regular', 'Regular'), ('family', 'Family'), ('staff', 'Staff')], default='regular', help_text='Family and staff accounts are charged at recipe cost price.', max_length=20),
        ),
    ]
