# Generated by Django 6.0.6 on 2026-07-16

import decimal
from decimal import Decimal

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0004_customer_account_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="credit_limit",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0"),
                help_text="Maximum allowed negative balance (base currency).",
                max_digits=12,
            ),
        ),
    ]
