# Generated by Django 6.0.6 on 2026-07-23 07:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0008_branch_allow_negative_stock'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('action', models.CharField(choices=[('update', 'Update'), ('delete', 'Delete'), ('deactivate', 'Deactivate')], max_length=20)),
                ('entity_type', models.CharField(db_index=True, max_length=64)),
                ('entity_id', models.CharField(max_length=64)),
                ('entity_label', models.CharField(blank=True, max_length=255)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('request_path', models.CharField(blank=True, max_length=255)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='branches.branch')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['entity_type', 'entity_id'], name='audit_audit_entity__0bff9a_idx'), models.Index(fields=['branch', 'created_at'], name='audit_audit_branch__71fa56_idx'), models.Index(fields=['actor', 'created_at'], name='audit_audit_actor_i_58da28_idx')],
            },
        ),
    ]
