# Generated by Django 6.0.6 on 2026-06-23 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='vat_number',
            field=models.CharField(blank=True, help_text='ZIMRA VAT registration number. Leave blank for non-VAT suppliers.', max_length=20),
        ),
    ]
