# Generated by Django 6.0.6 on 2026-07-16 10:18

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0002_supplier_vat_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorderline',
            name='quantity',
            field=models.DecimalField(decimal_places=4, max_digits=16),
        ),
        migrations.AlterField(
            model_name='purchaseorderline',
            name='unit_cost',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=16),
        ),
    ]
