# Generated by Django 6.0.6 on 2026-06-09 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_product_remaining_qty_tax_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='fiscal_tax_code',
            field=models.CharField(blank=True, help_text='ZIMRA tax code, e.g. E (standard rated) or B (zero rated).', max_length=5),
        ),
        migrations.AddField(
            model_name='product',
            name='fiscal_tax_id',
            field=models.PositiveIntegerField(blank=True, help_text="ZIMRA tax ID for this product's tax category.", null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='hs_code',
            field=models.CharField(blank=True, default='00000000', help_text='Harmonized System code for fiscal receipts.', max_length=20),
        ),
    ]
