# Generated by Django 6.0.6 on 2026-06-09 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_product_fiscal_tax_code_product_fiscal_tax_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='is_asset',
            field=models.BooleanField(default=False, help_text='Assets are included in monthly stock takes only, not daily counts.'),
        ),
    ]
