# Generated by Django 6.0.6 on 2026-07-06 08:02

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


def seed_addons(apps, schema_editor):
    from catalog.menu_addons import seed_menu_addons

    seed_menu_addons(link_products=True)


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_productcategory_is_asset'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuAddonGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('selection_type', models.CharField(choices=[('multiple', 'Multiple'), ('single', 'Single')], default='multiple', max_length=20)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MenuAddon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('selling_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addons', to='catalog.menuaddongroup')),
            ],
            options={
                'ordering': ['sort_order', 'name'],
                'constraints': [models.UniqueConstraint(fields=('group', 'name'), name='catalog_menuaddon_unique_group_name')],
            },
        ),
        migrations.CreateModel(
            name='ProductMenuAddonGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_links', to='catalog.menuaddongroup')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addon_group_links', to='catalog.product')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('product', 'group'), name='catalog_productmenuaddongroup_unique')],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='daily_stock_take',
            field=models.BooleanField(
                default=False,
                help_text='Include this product in daily stock counts at branches that stock it.',
            ),
        ),
        migrations.RunPython(seed_addons, migrations.RunPython.noop),
    ]
