# Generated by Django 6.0.6 on 2026-07-28 06:16

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_productcategory_show_on_pos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='remaining_qty',
            field=models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12),
        ),
    ]
