# Generated by Django 6.0.6 on 2026-08-03 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_quantity_three_dp'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='group_category',
            field=models.ForeignKey(blank=True, help_text='Optional grouping for ingredients. Ingredients stay under Ingredients / Branch Ingredients for stock; this picks a product category for display and filtering.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='grouped_products', to='catalog.productcategory'),
        ),
    ]
