# Generated by Django 6.0.6 on 2026-06-08 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_amount_paid_order_payment_fee_amount_and_more'),
        ('payments', '0002_currency_name_unique'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_fee_amount',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_method',
        ),
        migrations.AddField(
            model_name='order',
            name='exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Exchange rate applied at payment (units per 1 base unit).', max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='payments.currency'),
        ),
    ]
