# Generated by Django 6.0.6 on 2026-06-09 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0004_branch_code'),
        ('orders', '0003_remove_order_payment_fee_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='receipt_number',
            field=models.CharField(blank=True, help_text='Assigned at payment, e.g. HIG0906267 (code + DDMMYY + daily count).', max_length=20, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='BranchReceiptSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_date', models.DateField(blank=True, null=True)),
                ('daily_count', models.PositiveIntegerField(default=0)),
                ('branch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receipt_sequence', to='branches.branch')),
            ],
            options={
                'verbose_name': 'branch receipt sequence',
                'verbose_name_plural': 'branch receipt sequences',
            },
        ),
    ]
