# Generated by Django 6.0.6 on 2026-06-23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0009_order_fiscal_approval"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                blank=True,
                choices=[("cash", "Cash"), ("account", "Customer account")],
                default="",
                help_text="How the order was paid (cash or customer account).",
                max_length=20,
            ),
        ),
    ]
