# Generated by Django 6.0.6 on 2026-07-10 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_menu_addons'),
        ('payments', '0003_delete_paymentmethod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('bank', 'Bank'), ('ecocash', 'EcoCash'), ('account', 'Customer account'), ('multi', 'Split payment')], default='', help_text='How the order was paid (cash, bank, EcoCash, account, or split).', max_length=20),
        ),
        migrations.CreateModel(
            name='OrderPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank'), ('ecocash', 'EcoCash')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('exchange_rate', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_payments', to='payments.currency')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='orders.order')),
            ],
            options={
                'ordering': ['id'],
                'constraints': [models.UniqueConstraint(fields=('order', 'method'), name='orders_orderpayment_unique_order_method')],
            },
        ),
    ]
