# Generated by Django 6.0.6 on 2026-07-10 05:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0008_branch_allow_negative_stock'),
        ('orders', '0014_orderpayment_unique_currency'),
        ('payments', '0003_delete_paymentmethod'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DayEndClose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField(help_text='Business day this cash-up covers.')),
                ('closed_at', models.DateTimeField(auto_now=True)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('order_count', models.PositiveIntegerField(default=0)),
                ('gross_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('expenses_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('variance_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('has_counted_entries', models.BooleanField(default=False)),
                ('activity_snapshot', models.JSONField(blank=True, default=dict, help_text='Frozen day-end report payload at close time.')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='day_end_closes', to='branches.branch')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='day_end_closes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-report_date', '-closed_at'],
            },
        ),
        migrations.CreateModel(
            name='DayEndCashLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('deposits_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('expenses_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('expected_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('net_expected_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('counted_total', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('variance', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='day_end_cash_lines', to='payments.currency')),
                ('day_end', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_lines', to='orders.dayendclose')),
            ],
            options={
                'ordering': ['currency__name'],
            },
        ),
        migrations.AddConstraint(
            model_name='dayendclose',
            constraint=models.UniqueConstraint(fields=('branch', 'report_date'), name='orders_dayendclose_unique_branch_date'),
        ),
        migrations.AddConstraint(
            model_name='dayendcashline',
            constraint=models.UniqueConstraint(fields=('day_end', 'currency'), name='orders_dayendcashline_unique_day_currency'),
        ),
    ]
