# Generated by Django 6.0.6 on 2026-06-09 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0002_branch_fiscalization_enabled'),
        ('orders', '0003_remove_order_payment_fee_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchFiscalState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_counter', models.PositiveIntegerField(default=0)),
                ('receipt_global_no', models.PositiveIntegerField(default=0)),
                ('invoice_sequence', models.PositiveIntegerField(default=0)),
                ('branch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fiscal_state', to='branches.branch')),
            ],
            options={
                'verbose_name': 'branch fiscal state',
                'verbose_name_plural': 'branch fiscal states',
            },
        ),
        migrations.CreateModel(
            name='FiscalReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_counter', models.PositiveIntegerField()),
                ('receipt_global_no', models.PositiveIntegerField()),
                ('invoice_no', models.CharField(max_length=32)),
                ('payload', models.JSONField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('submitted', 'Submitted'), ('accepted', 'Accepted'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('zimra_response', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fiscal_receipts', to='branches.branch')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fiscal_receipt', to='orders.order')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
