# Generated by Django 6.0.6 on 2026-06-09 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zimra_fiscal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiscalreceipt',
            name='device_branch_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='fiscalreceipt',
            name='device_serial_no',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='fiscalreceipt',
            name='fiscal_day_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fiscalreceipt',
            name='fiscal_invoice_number',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='fiscalreceipt',
            name='qr_string',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='fiscalreceipt',
            name='qr_url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='fiscalreceipt',
            name='verification_code',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
